//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZUART.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM1")]
        public string cbbComList {
            get {
                return ((string)(this["cbbComList"]));
            }
            set {
                this["cbbComList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("115200")]
        public string cbbBaudRate {
            get {
                return ((string)(this["cbbBaudRate"]));
            }
            set {
                this["cbbBaudRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public string cbbDataBits {
            get {
                return ((string)(this["cbbDataBits"]));
            }
            set {
                this["cbbDataBits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string cbbStopBits {
            get {
                return ((string)(this["cbbStopBits"]));
            }
            set {
                this["cbbStopBits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string cbbParity {
            get {
                return ((string)(this["cbbParity"]));
            }
            set {
                this["cbbParity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ZUART")]
        public string txtSendData {
            get {
                return ((string)(this["txtSendData"]));
            }
            set {
                this["txtSendData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkAutoLine {
            get {
                return ((bool)(this["chkAutoLine"]));
            }
            set {
                this["chkAutoLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkShowTime {
            get {
                return ((bool)(this["chkShowTime"]));
            }
            set {
                this["chkShowTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkRecSend {
            get {
                return ((bool)(this["chkRecSend"]));
            }
            set {
                this["chkRecSend"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkfromFileSend {
            get {
                return ((bool)(this["chkfromFileSend"]));
            }
            set {
                this["chkfromFileSend"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkAutoAddSend {
            get {
                return ((bool)(this["chkAutoAddSend"]));
            }
            set {
                this["chkAutoAddSend"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkAutoCleanSend {
            get {
                return ((bool)(this["chkAutoCleanSend"]));
            }
            set {
                this["chkAutoCleanSend"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkAutoSend {
            get {
                return ((bool)(this["chkAutoSend"]));
            }
            set {
                this["chkAutoSend"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public string txtAutoSendms {
            get {
                return ((string)(this["txtAutoSendms"]));
            }
            set {
                this["txtAutoSendms"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool rbtnHex {
            get {
                return ((bool)(this["rbtnHex"]));
            }
            set {
                this["rbtnHex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool rbtnASCII {
            get {
                return ((bool)(this["rbtnASCII"]));
            }
            set {
                this["rbtnASCII"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool rbtnUTF8 {
            get {
                return ((bool)(this["rbtnUTF8"]));
            }
            set {
                this["rbtnUTF8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool rbtnUnicode {
            get {
                return ((bool)(this["rbtnUnicode"]));
            }
            set {
                this["rbtnUnicode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool rbtnSendHex {
            get {
                return ((bool)(this["rbtnSendHex"]));
            }
            set {
                this["rbtnSendHex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool rbtnSendASCII {
            get {
                return ((bool)(this["rbtnSendASCII"]));
            }
            set {
                this["rbtnSendASCII"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool rbtnSendUTF8 {
            get {
                return ((bool)(this["rbtnSendUTF8"]));
            }
            set {
                this["rbtnSendUTF8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool rbtnSendUnicode {
            get {
                return ((bool)(this["rbtnSendUnicode"]));
            }
            set {
                this["rbtnSendUnicode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ListSend_Text0 {
            get {
                return ((string)(this["ListSend_Text0"]));
            }
            set {
                this["ListSend_Text0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ListSend_Hex0 {
            get {
                return ((bool)(this["ListSend_Hex0"]));
            }
            set {
                this["ListSend_Hex0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ListSend_Text1 {
            get {
                return ((string)(this["ListSend_Text1"]));
            }
            set {
                this["ListSend_Text1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ListSend_Text2 {
            get {
                return ((string)(this["ListSend_Text2"]));
            }
            set {
                this["ListSend_Text2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ListSend_Text3 {
            get {
                return ((string)(this["ListSend_Text3"]));
            }
            set {
                this["ListSend_Text3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ListSend_Text4 {
            get {
                return ((string)(this["ListSend_Text4"]));
            }
            set {
                this["ListSend_Text4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ListSend_Text5 {
            get {
                return ((string)(this["ListSend_Text5"]));
            }
            set {
                this["ListSend_Text5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ListSend_Text6 {
            get {
                return ((string)(this["ListSend_Text6"]));
            }
            set {
                this["ListSend_Text6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ListSend_Text7 {
            get {
                return ((string)(this["ListSend_Text7"]));
            }
            set {
                this["ListSend_Text7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ListSend_Text8 {
            get {
                return ((string)(this["ListSend_Text8"]));
            }
            set {
                this["ListSend_Text8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ListSend_Text9 {
            get {
                return ((string)(this["ListSend_Text9"]));
            }
            set {
                this["ListSend_Text9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ListSend_Text10 {
            get {
                return ((string)(this["ListSend_Text10"]));
            }
            set {
                this["ListSend_Text10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ListSend_Text11 {
            get {
                return ((string)(this["ListSend_Text11"]));
            }
            set {
                this["ListSend_Text11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ListSend_Text12 {
            get {
                return ((string)(this["ListSend_Text12"]));
            }
            set {
                this["ListSend_Text12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ListSend_Text13 {
            get {
                return ((string)(this["ListSend_Text13"]));
            }
            set {
                this["ListSend_Text13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ListSend_Text14 {
            get {
                return ((string)(this["ListSend_Text14"]));
            }
            set {
                this["ListSend_Text14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ListSend_Text15 {
            get {
                return ((string)(this["ListSend_Text15"]));
            }
            set {
                this["ListSend_Text15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ListSend_Text16 {
            get {
                return ((string)(this["ListSend_Text16"]));
            }
            set {
                this["ListSend_Text16"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ListSend_Text17 {
            get {
                return ((string)(this["ListSend_Text17"]));
            }
            set {
                this["ListSend_Text17"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ListSend_Text18 {
            get {
                return ((string)(this["ListSend_Text18"]));
            }
            set {
                this["ListSend_Text18"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ListSend_Text19 {
            get {
                return ((string)(this["ListSend_Text19"]));
            }
            set {
                this["ListSend_Text19"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ListSend_Text20 {
            get {
                return ((string)(this["ListSend_Text20"]));
            }
            set {
                this["ListSend_Text20"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ListSend_Text21 {
            get {
                return ((string)(this["ListSend_Text21"]));
            }
            set {
                this["ListSend_Text21"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ListSend_Text22 {
            get {
                return ((string)(this["ListSend_Text22"]));
            }
            set {
                this["ListSend_Text22"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ListSend_Text23 {
            get {
                return ((string)(this["ListSend_Text23"]));
            }
            set {
                this["ListSend_Text23"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ListSend_Text24 {
            get {
                return ((string)(this["ListSend_Text24"]));
            }
            set {
                this["ListSend_Text24"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ListSend_Text25 {
            get {
                return ((string)(this["ListSend_Text25"]));
            }
            set {
                this["ListSend_Text25"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ListSend_Text26 {
            get {
                return ((string)(this["ListSend_Text26"]));
            }
            set {
                this["ListSend_Text26"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ListSend_Text27 {
            get {
                return ((string)(this["ListSend_Text27"]));
            }
            set {
                this["ListSend_Text27"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ListSend_Text28 {
            get {
                return ((string)(this["ListSend_Text28"]));
            }
            set {
                this["ListSend_Text28"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ListSend_Text29 {
            get {
                return ((string)(this["ListSend_Text29"]));
            }
            set {
                this["ListSend_Text29"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ListSend_Text30 {
            get {
                return ((string)(this["ListSend_Text30"]));
            }
            set {
                this["ListSend_Text30"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ListSend_Text31 {
            get {
                return ((string)(this["ListSend_Text31"]));
            }
            set {
                this["ListSend_Text31"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ListSend_Text32 {
            get {
                return ((string)(this["ListSend_Text32"]));
            }
            set {
                this["ListSend_Text32"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ListSend_Text33 {
            get {
                return ((string)(this["ListSend_Text33"]));
            }
            set {
                this["ListSend_Text33"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ListSend_Text34 {
            get {
                return ((string)(this["ListSend_Text34"]));
            }
            set {
                this["ListSend_Text34"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ListSend_Text35 {
            get {
                return ((string)(this["ListSend_Text35"]));
            }
            set {
                this["ListSend_Text35"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ListSend_Text36 {
            get {
                return ((string)(this["ListSend_Text36"]));
            }
            set {
                this["ListSend_Text36"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ListSend_Text37 {
            get {
                return ((string)(this["ListSend_Text37"]));
            }
            set {
                this["ListSend_Text37"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ListSend_Text38 {
            get {
                return ((string)(this["ListSend_Text38"]));
            }
            set {
                this["ListSend_Text38"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ListSend_Text39 {
            get {
                return ((string)(this["ListSend_Text39"]));
            }
            set {
                this["ListSend_Text39"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ListSend_Text40 {
            get {
                return ((string)(this["ListSend_Text40"]));
            }
            set {
                this["ListSend_Text40"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ListSend_Text41 {
            get {
                return ((string)(this["ListSend_Text41"]));
            }
            set {
                this["ListSend_Text41"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ListSend_Text42 {
            get {
                return ((string)(this["ListSend_Text42"]));
            }
            set {
                this["ListSend_Text42"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ListSend_Text43 {
            get {
                return ((string)(this["ListSend_Text43"]));
            }
            set {
                this["ListSend_Text43"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ListSend_Text44 {
            get {
                return ((string)(this["ListSend_Text44"]));
            }
            set {
                this["ListSend_Text44"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ListSend_Text45 {
            get {
                return ((string)(this["ListSend_Text45"]));
            }
            set {
                this["ListSend_Text45"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ListSend_Text46 {
            get {
                return ((string)(this["ListSend_Text46"]));
            }
            set {
                this["ListSend_Text46"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ListSend_Text47 {
            get {
                return ((string)(this["ListSend_Text47"]));
            }
            set {
                this["ListSend_Text47"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ListSend_Text48 {
            get {
                return ((string)(this["ListSend_Text48"]));
            }
            set {
                this["ListSend_Text48"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ListSend_Text49 {
            get {
                return ((string)(this["ListSend_Text49"]));
            }
            set {
                this["ListSend_Text49"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ListSend_Hex1 {
            get {
                return ((bool)(this["ListSend_Hex1"]));
            }
            set {
                this["ListSend_Hex1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ListSend_Hex2 {
            get {
                return ((bool)(this["ListSend_Hex2"]));
            }
            set {
                this["ListSend_Hex2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ListSend_Hex3 {
            get {
                return ((bool)(this["ListSend_Hex3"]));
            }
            set {
                this["ListSend_Hex3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ListSend_Hex4 {
            get {
                return ((bool)(this["ListSend_Hex4"]));
            }
            set {
                this["ListSend_Hex4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ListSend_Hex5 {
            get {
                return ((bool)(this["ListSend_Hex5"]));
            }
            set {
                this["ListSend_Hex5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ListSend_Hex6 {
            get {
                return ((bool)(this["ListSend_Hex6"]));
            }
            set {
                this["ListSend_Hex6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ListSend_Hex7 {
            get {
                return ((bool)(this["ListSend_Hex7"]));
            }
            set {
                this["ListSend_Hex7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ListSend_Hex8 {
            get {
                return ((bool)(this["ListSend_Hex8"]));
            }
            set {
                this["ListSend_Hex8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ListSend_Hex9 {
            get {
                return ((bool)(this["ListSend_Hex9"]));
            }
            set {
                this["ListSend_Hex9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ListSend_Hex10 {
            get {
                return ((bool)(this["ListSend_Hex10"]));
            }
            set {
                this["ListSend_Hex10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ListSend_Hex11 {
            get {
                return ((bool)(this["ListSend_Hex11"]));
            }
            set {
                this["ListSend_Hex11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ListSend_Hex12 {
            get {
                return ((bool)(this["ListSend_Hex12"]));
            }
            set {
                this["ListSend_Hex12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ListSend_Hex13 {
            get {
                return ((bool)(this["ListSend_Hex13"]));
            }
            set {
                this["ListSend_Hex13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ListSend_Hex14 {
            get {
                return ((bool)(this["ListSend_Hex14"]));
            }
            set {
                this["ListSend_Hex14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ListSend_Hex15 {
            get {
                return ((bool)(this["ListSend_Hex15"]));
            }
            set {
                this["ListSend_Hex15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ListSend_Hex16 {
            get {
                return ((bool)(this["ListSend_Hex16"]));
            }
            set {
                this["ListSend_Hex16"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ListSend_Hex17 {
            get {
                return ((bool)(this["ListSend_Hex17"]));
            }
            set {
                this["ListSend_Hex17"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ListSend_Hex18 {
            get {
                return ((bool)(this["ListSend_Hex18"]));
            }
            set {
                this["ListSend_Hex18"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ListSend_Hex19 {
            get {
                return ((bool)(this["ListSend_Hex19"]));
            }
            set {
                this["ListSend_Hex19"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ListSend_Hex20 {
            get {
                return ((bool)(this["ListSend_Hex20"]));
            }
            set {
                this["ListSend_Hex20"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ListSend_Hex21 {
            get {
                return ((bool)(this["ListSend_Hex21"]));
            }
            set {
                this["ListSend_Hex21"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ListSend_Hex22 {
            get {
                return ((bool)(this["ListSend_Hex22"]));
            }
            set {
                this["ListSend_Hex22"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ListSend_Hex23 {
            get {
                return ((bool)(this["ListSend_Hex23"]));
            }
            set {
                this["ListSend_Hex23"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ListSend_Hex24 {
            get {
                return ((bool)(this["ListSend_Hex24"]));
            }
            set {
                this["ListSend_Hex24"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ListSend_Hex25 {
            get {
                return ((bool)(this["ListSend_Hex25"]));
            }
            set {
                this["ListSend_Hex25"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ListSend_Hex26 {
            get {
                return ((bool)(this["ListSend_Hex26"]));
            }
            set {
                this["ListSend_Hex26"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ListSend_Hex27 {
            get {
                return ((bool)(this["ListSend_Hex27"]));
            }
            set {
                this["ListSend_Hex27"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ListSend_Hex28 {
            get {
                return ((bool)(this["ListSend_Hex28"]));
            }
            set {
                this["ListSend_Hex28"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ListSend_Hex29 {
            get {
                return ((bool)(this["ListSend_Hex29"]));
            }
            set {
                this["ListSend_Hex29"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ListSend_Hex30 {
            get {
                return ((bool)(this["ListSend_Hex30"]));
            }
            set {
                this["ListSend_Hex30"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ListSend_Hex31 {
            get {
                return ((bool)(this["ListSend_Hex31"]));
            }
            set {
                this["ListSend_Hex31"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ListSend_Hex32 {
            get {
                return ((bool)(this["ListSend_Hex32"]));
            }
            set {
                this["ListSend_Hex32"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ListSend_Hex33 {
            get {
                return ((bool)(this["ListSend_Hex33"]));
            }
            set {
                this["ListSend_Hex33"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ListSend_Hex34 {
            get {
                return ((bool)(this["ListSend_Hex34"]));
            }
            set {
                this["ListSend_Hex34"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ListSend_Hex35 {
            get {
                return ((bool)(this["ListSend_Hex35"]));
            }
            set {
                this["ListSend_Hex35"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ListSend_Hex36 {
            get {
                return ((bool)(this["ListSend_Hex36"]));
            }
            set {
                this["ListSend_Hex36"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ListSend_Hex37 {
            get {
                return ((bool)(this["ListSend_Hex37"]));
            }
            set {
                this["ListSend_Hex37"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ListSend_Hex38 {
            get {
                return ((bool)(this["ListSend_Hex38"]));
            }
            set {
                this["ListSend_Hex38"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ListSend_Hex39 {
            get {
                return ((bool)(this["ListSend_Hex39"]));
            }
            set {
                this["ListSend_Hex39"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ListSend_Hex40 {
            get {
                return ((bool)(this["ListSend_Hex40"]));
            }
            set {
                this["ListSend_Hex40"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ListSend_Hex41 {
            get {
                return ((bool)(this["ListSend_Hex41"]));
            }
            set {
                this["ListSend_Hex41"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ListSend_Hex42 {
            get {
                return ((bool)(this["ListSend_Hex42"]));
            }
            set {
                this["ListSend_Hex42"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ListSend_Hex43 {
            get {
                return ((bool)(this["ListSend_Hex43"]));
            }
            set {
                this["ListSend_Hex43"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ListSend_Hex44 {
            get {
                return ((bool)(this["ListSend_Hex44"]));
            }
            set {
                this["ListSend_Hex44"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ListSend_Hex45 {
            get {
                return ((bool)(this["ListSend_Hex45"]));
            }
            set {
                this["ListSend_Hex45"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ListSend_Hex46 {
            get {
                return ((bool)(this["ListSend_Hex46"]));
            }
            set {
                this["ListSend_Hex46"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ListSend_Hex47 {
            get {
                return ((bool)(this["ListSend_Hex47"]));
            }
            set {
                this["ListSend_Hex47"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ListSend_Hex48 {
            get {
                return ((bool)(this["ListSend_Hex48"]));
            }
            set {
                this["ListSend_Hex48"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ListSend_Hex49 {
            get {
                return ((bool)(this["ListSend_Hex49"]));
            }
            set {
                this["ListSend_Hex49"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkTrans {
            get {
                return ((bool)(this["chkTrans"]));
            }
            set {
                this["chkTrans"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Checked")]
        public global::System.Windows.Forms.CheckState menuItemSendKey1 {
            get {
                return ((global::System.Windows.Forms.CheckState)(this["menuItemSendKey1"]));
            }
            set {
                this["menuItemSendKey1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Unchecked")]
        public global::System.Windows.Forms.CheckState menuItemSendKey2 {
            get {
                return ((global::System.Windows.Forms.CheckState)(this["menuItemSendKey2"]));
            }
            set {
                this["menuItemSendKey2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Unchecked")]
        public global::System.Windows.Forms.CheckState menuItemSendKey3 {
            get {
                return ((global::System.Windows.Forms.CheckState)(this["menuItemSendKey3"]));
            }
            set {
                this["menuItemSendKey3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Unchecked")]
        public global::System.Windows.Forms.CheckState menuItemSendKey4 {
            get {
                return ((global::System.Windows.Forms.CheckState)(this["menuItemSendKey4"]));
            }
            set {
                this["menuItemSendKey4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BatchSendList {
            get {
                return ((string)(this["BatchSendList"]));
            }
            set {
                this["BatchSendList"] = value;
            }
        }
    }
}
